### ISSUE TITLE
Getting an error for version mismatch.

### ISSUE THREAD

**Issue by zkanda** [iron-io/ironcli#112]
Hello,

For some reason, iron-cli stop working for me today, I'm getting this errors but not sure how to fix it on my end.

```
400 Bad Request: API version mismatch: '2', expected version: '3'. please ensure that the host  in your configuration is for the intended API and that you are using the correct library version for version 3of this API. If this makes no sense, please contact <support@iron.io> with a better error message recommendation and for assistance. You may simply need to add a section to your iron.json for the intended service, see docs here: http://dev.iron.io/worker/reference/configuration/
```

**Comment by rdallman** [comment]
the error message really tries :) open to suggestions, can't win with that thing.

usually when this happens you're hitting an mq v3 host to try to use worker. per the error message, try adding a section for `"iron_mq"` to your `iron.json` or use `IRON_MQ_HOST` rather than changing `"host"` in the top level and attempting to use worker commands with it.

closing as not a cli issue, feel free to open a ticket at support@iron.io. above should fix.

**Comment by zkanda** [comment]
From my investigation, using `~/.iron.json` doesn't default to v3. I have something like this:

```
{
    "token": "MY_TOKEN",
    "project_id": "MY_PROJECT_ID"
 }
```

Then I switch to using environment variable and it's now working again.
For other people that might stumble into this, if you want to keep using the json file, you probably need to add `api_version` in there. Reference: http://dev.iron.io/worker/reference/configuration-iron-json/index.html#accepted_values
