### ISSUE TITLE
Better installation methods should have bug-level priority

### ISSUE THREAD

**Issue by ches** [iron-io/ironcli#40]
`curl` piped to `sh` *and you're not even serving that script with TLS/SSL*? C'mon folks, it's downloading a pre-built binary and putting it on a path :smile:  I'm sure Windows is a bigger pain, but a Homebrew formula and throwing [fpm] at this should literally be doable in an hour even if you've never packaged something with them before…

Sorry to sound surly here, but I worry for sake of your less informed or less vigilant new customers. You have such a polished suite of products and this is not a befitting first impression.

[fpm]: https://github.com/jordansissel/fpm

**Comment by rdallman** [comment]
thanks for opening the issue. the curl pipe sh seems to offend certain people more than others (rust (famously) has a large disclaimer about the whole thing in their install guide [here](http://doc.rust-lang.org/book/installing-rust.html)). we do need to add SSL to the endpoint as we're not showing a three step download, inspect and run method for installs; thanks for highlighting this, it's just something that slipped through the cracks since moving from beta into prod.

So, how about we add a disclaimer (ala rust) and SSL? would this make a better impression? not just to please you -- just trying to figure out what the best install experience would be? Personally, I think the majority will just run the curl | sh script and not think anything of it (maybe this _is_ the problem). I agree we should offer / highlight alternatives better.

we do plan to add more convenient installers for each package but would love any help from the community in the mean time as we do not have anybody working on this full time at the moment (it is a priority to polish this in the coming weeks). 

again, thanks for the feedback. we will try to improve the experience and look forward to any further feedback.

**Comment by treeder** [comment]
There's also the docker way which doesn't require an install (other than docker).  Needs a merge: https://github.com/iron-io/ironcli/pull/37

**Comment by ches** [comment]
Thanks for the responsiveness guys. SSL is the main worry for me, many people will surely just run it blindly without noticing or caring about the difference but at least you can do a lot to help those unwitting people avoid a malicious man-in-the-middle (a published `curl http:// | sh` instruction represents a juicy target for such malicious people).

Being pragmatic I'm not terribly offended by `curl | sh` personally, but absolutely not without SSL, and preferably without a redirect (being pragmatic but aware, I can at least spot check it first by leaving off the `| sh`). I do think a disclaimer like Rust's is a good precedent, and they keep it pretty short and non-patronizing.

**Comment by ches** [comment]
:+1: for the `https://` and new disclaimer in the README :smiley:

**Comment by rdallman** [comment]
closing this for #42
